version: "3.8"
services:
  php-webserver:
    build:
      context: .
      dockerfile: ./php-webserver/Dockerfile
    ports:
      - "8080:80"
    restart: on-failure
    env_file: "./php-webserver/.env"

  java-microservice:
    build:
      context: .
      dockerfile: ./java-microservice/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - EUREKA_SERVER=http://eureka-server:8761/eureka/

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  eureka-server:
    image: eureka-server:latest
    ports:
      - "8761:8761"
